POST http://localhost:3001/auth/register
Content-Type: application/json

{
  "name": "books limited",
  "email": "kotarisudeep@gmail.com",
  "password": "1234",
  "books":{
    "title":"once upon a time"
  }
}

###
POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "email": "kotarisudeep@gmail.com",
    "password": "1234"
}
